quarkus.http.access-log.enabled=true
quarkus.http.host=0.0.0.0
quarkus.log.category."WebApplicationException".level=DEBUG

quarkus.neo4j.uri=bolt://neo4j:7687
quarkus.neo4j.authentication.username=neo4j
quarkus.neo4j.authentication.password=devpassword

# app properties
llm.base.url=${OLLAMA_BASE_URL:http://ollama:11434}/api/
llm.model=${OLLAMA_MODEL:granite4.1:3b}

observability.log.raw-request=true
observability.log.command-payload=true
observability.log.llm-prompt=false
observability.log.llm-response=true
observability.log.domain-events=true

req.orchestration.enabled=true
req.graphchange.enabled=true
